# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 * * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: jenslys
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Europe/Norway
          plugin_isocalendar: no
          plugin_isocalendar_duration: half-year
          plugin_languages: no
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent.days: 14
          plugin_languages_recent.load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_pagespeed: yes
          plugin_pagespeed_url: https://lystad.io/
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_projects: yes
          plugin_projects_limit: 10
